version: '3.7'
services:
  anylog-operator:
    image: anylogco/anylog-node:latest
    restart: always
    env_file:
      - anylog_operator.env
    environment:
      INIT_TYPE: prod
    container_name: anylog-operator
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - anylog-operator-anylog:/app/AnyLog-Network/anylog
      - anylog-operator-blockchain:/app/AnyLog-Network/blockchain
      - anylog-operator-data:/app/AnyLog-Network/data
      - anylog-operator-local-scripts:/app/deployment-scripts
volumes:
  anylog-operator-anylog:
  anylog-operator-blockchain:
  anylog-operator-data:
  anylog-operator-local-scripts: