version: '3.7'
services:
  remote-cli:
      image: anylogco/remote-cli:latest
      container_name: remote-cli
      restart: always
      stdin_open: true
      tty: true
      network_mode: "host"
      environment:
        - CONN_IP=0.0.0.0
        - CLI_PORT=31800
      volumes:
        - remote-cli:/app/Remote-CLI/djangoProject/static/json
        - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
volumes:
  anylog-query-anylog:
  anylog-query-blockchain:
  anylog-query-data:
  anylog-query-local-scripts:
  remote-cli:
  remote-cli-current:
